// <auto-generated />
using System;
using FinalProjectCodeFirstApproch.Models.JunctionForAllClass;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProjectCodeFirstApproch.Migrations
{
    [DbContext(typeof(PoliceStationManagementDbContext))]
    partial class PoliceStationManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinalProjectCodeFirstApproch.Models.Criminal_Management.CriminalActivity", b =>
                {
                    b.Property<int>("CriminalActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CriminalActivityId"));

                    b.Property<int?>("CriminalId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CriminalActivityId");

                    b.HasIndex("CriminalId");

                    b.ToTable("CriminalActivities");
                });

            modelBuilder.Entity("FinalProjectCodeFirstApproch.Models.Criminal_Management.CriminalContact", b =>
                {
                    b.Property<int>("CriminalContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CriminalContactId"));

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CriminalId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CriminalContactId");

                    b.HasIndex("CriminalId");

                    b.ToTable("CriminalContacts");
                });

            modelBuilder.Entity("FinalProjectCodeFirstApproch.Models.Criminal_Management.CriminalInfo", b =>
                {
                    b.Property<int>("CriminalInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CriminalInfoId"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("CaseId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SuspectId")
                        .HasColumnType("int");

                    b.HasKey("CriminalInfoId");

                    b.HasIndex("CaseId");

                    b.HasIndex("SuspectId");

                    b.ToTable("Criminals");
                });

            modelBuilder.Entity("FinalProjectCodeFirstApproch.Models.Criminal_Management.Prison", b =>
                {
                    b.Property<int>("PrisonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrisonId"));

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrisonName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PrisonId");

                    b.ToTable("Prisons");
                });

            modelBuilder.Entity("FinalProjectCodeFirstApproch.Models.Criminal_Management.PrisonRecords", b =>
                {
                    b.Property<int>("PrisonRecordsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrisonRecordsId"));

                    b.Property<int?>("CriminalId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EntryDate")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<int?>("PrisonId")
                        .HasColumnType("int");

                    b.Property<string>("ReasonForImprisonment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReleaseDate")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PrisonRecordsId");

                    b.HasIndex("CriminalId");

                    b.HasIndex("PrisonId");

                    b.ToTable("PrisonRecords");
                });

            modelBuilder.Entity("FinalProjectCodeFirstApproch.Models.Investigation_Management.InvestigationInfo", b =>
                {
                    b.Property<int>("InvestigationInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvestigationInfoId"));

                    b.Property<int?>("CaseId")
                        .HasColumnType("int");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OfficerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InvestigationInfoId");

                    b.HasIndex("CaseId");

                    b.HasIndex("OfficerId");

                    b.ToTable("InvestigationInfos");
                });

            modelBuilder.Entity("FinalProjectCodeFirstApproch.Models.Investigation_Management.ReportAnalysis", b =>
                {
                    b.Property<int>("ReportAnalysisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportAnalysisId"));

                    b.Property<string>("AnalysisResults")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CaseId")
                        .HasColumnType("int");

                    b.Property<string>("Conclusions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OfficerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReportingDate")
                        .IsRequired()
                        .HasColumnType("date");

                    b.HasKey("ReportAnalysisId");

                    b.HasIndex("CaseId");

                    b.HasIndex("OfficerId");

                    b.ToTable("ReportAnalyses");
                });

            modelBuilder.Entity("FinalProjectCodeFirstApproch.Models.Police_Management.CaseInfo", b =>
                {
                    b.Property<int>("CaseInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CaseInfoId"));

                    b.Property<int?>("PoliceId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SuspectId")
                        .HasColumnType("int");

                    b.Property<int?>("VictimId")
                        .HasColumnType("int");

                    b.Property<int?>("WitnessId")
                        .HasColumnType("int");

                    b.HasKey("CaseInfoId");

                    b.HasIndex("PoliceId");

                    b.HasIndex("SuspectId");

                    b.HasIndex("VictimId");

                    b.HasIndex("WitnessId");

                    b.ToTable("CaseInfos");
                });

            modelBuilder.Entity("FinalProjectCodeFirstApproch.Models.Police_Management.ReportsInfo", b =>
                {
                    b.Property<int>("ReportsInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportsInfoId"));

                    b.Property<int?>("CaseId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OfficerId")
                        .HasColumnType("int");

                    b.HasKey("ReportsInfoId");

                    b.HasIndex("CaseId");

                    b.HasIndex("OfficerId");

                    b.ToTable("ReportsInfos");
                });

            modelBuilder.Entity("FinalProjectCodeFirstApproch.Models.Police_Management.ShiftInfo", b =>
                {
                    b.Property<int>("ShiftInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShiftInfoId"));

                    b.Property<DateTime?>("EndTime")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<string>("ShiftName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartTime")
                        .IsRequired()
                        .HasColumnType("date");

                    b.HasKey("ShiftInfoId");

                    b.ToTable("ShiftInfos");
                });

            modelBuilder.Entity("FinalProjectCodeFirstApproch.Models.Police_Management.StationInfo", b =>
                {
                    b.Property<int>("StationInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StationInfoId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PoliceId")
                        .HasColumnType("int");

                    b.Property<string>("StationName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StationInfoId");

                    b.HasIndex("PoliceId");

                    b.ToTable("StationInfos");
                });

            modelBuilder.Entity("FinalProjectCodeFirstApproch.Models.Suspect_Management.EvidenceInfo", b =>
                {
                    b.Property<int>("EvidenceInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EvidenceInfoId"));

                    b.Property<int?>("CaseId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CollectionDate")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EvidenceInfoId");

                    b.HasIndex("CaseId");

                    b.ToTable("EvidenceInfos");
                });

            modelBuilder.Entity("FinalProjectCodeFirstApproch.Models.Suspect_Management.InterrogationsInfo", b =>
                {
                    b.Property<int>("InterrogationsInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InterrogationsInfoId"));

                    b.Property<int?>("CaseId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OfficerId")
                        .HasColumnType("int");

                    b.Property<int?>("SuspectId")
                        .HasColumnType("int");

                    b.HasKey("InterrogationsInfoId");

                    b.HasIndex("CaseId");

                    b.HasIndex("OfficerId");

                    b.HasIndex("SuspectId");

                    b.ToTable("InterrogationsInfos");
                });

            modelBuilder.Entity("FinalProjectCodeFirstApproch.Models.Suspect_Management.SuspectContact", b =>
                {
                    b.Property<int>("SuspectContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SuspectContactId"));

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SuspectId")
                        .HasColumnType("int");

                    b.HasKey("SuspectContactId");

                    b.HasIndex("SuspectId");

                    b.ToTable("SuspectContacts");
                });

            modelBuilder.Entity("FinalProjectCodeFirstApproch.Models.Suspect_Management.SuspectInfo", b =>
                {
                    b.Property<int>("SuspectInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SuspectInfoId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VictimCaseApplyId")
                        .HasColumnType("int");

                    b.HasKey("SuspectInfoId");

                    b.HasIndex("VictimCaseApplyId");

                    b.ToTable("SuspectInfos");
                });

            modelBuilder.Entity("FinalProjectCodeFirstApproch.Models.System_Administration.PoliceIdentities", b =>
                {
                    b.Property<int>("PoliceIdentitiesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PoliceIdentitiesId"));

                    b.Property<string>("PoliceIdentitiesNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PoliceIdentitiesId");

                    b.ToTable("PoliceIdentitieses");
                });

            modelBuilder.Entity("FinalProjectCodeFirstApproch.Models.System_Administration.PoliceRegistration", b =>
                {
                    b.Property<int>("PoliceRegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PoliceRegistrationId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PoliceId")
                        .HasColumnType("int");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("StationId")
                        .HasColumnType("int");

                    b.HasKey("PoliceRegistrationId");

                    b.HasIndex("RoleId");

                    b.HasIndex("StationId");

                    b.ToTable("PoliceRegs");
                });

            modelBuilder.Entity("FinalProjectCodeFirstApproch.Models.System_Administration.PoliceRoles", b =>
                {
                    b.Property<int>("PoliceRolesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PoliceRolesId"));

                    b.Property<int>("PoliceUserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("PoliceRolesId");

                    b.ToTable("PoliceRoless");
                });

            modelBuilder.Entity("FinalProjectCodeFirstApproch.Models.System_Administration.PoliceUser", b =>
                {
                    b.Property<int>("PoliceUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PoliceUserId"));

                    b.Property<DateTime?>("DateOfBirth")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PoliceIdentitiesId")
                        .HasColumnType("int");

                    b.Property<string>("PoliceIdentitiesNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PoliceUserId");

                    b.HasIndex("PoliceIdentitiesId");

                    b.ToTable("PoliceUsers");
                });

            modelBuilder.Entity("FinalProjectCodeFirstApproch.Models.System_Administration.Roles", b =>
                {
                    b.Property<int>("RolesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolesId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RolesId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("FinalProjectCodeFirstApproch.Models.System_Administration.VictimRegistration", b =>
                {
                    b.Property<int>("VictimRegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VictimRegistrationId"));

                    b.Property<DateTime?>("DateOfBirth")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VictimRegistrationId");

                    b.ToTable("VictimRegs");
                });

            modelBuilder.Entity("FinalProjectCodeFirstApproch.Models.Victim_Management.CrimeType", b =>
                {
                    b.Property<int>("CrimeTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CrimeTypeId"));

                    b.Property<string>("CrimeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CrimeTypeId");

                    b.ToTable("CrimeTypes");
                });

            modelBuilder.Entity("FinalProjectCodeFirstApproch.Models.Victim_Management.VictimCaseApply", b =>
                {
                    b.Property<int>("VictimCaseApplyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VictimCaseApplyId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("CrimeDescription")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CrimeSpot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CrimeTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Nid")
                        .HasColumnType("bigint");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profession")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VictimCaseApplyId");

                    b.HasIndex("CrimeTypeId");

                    b.ToTable("VictimsCaseApplies");
                });

            modelBuilder.Entity("FinalProjectCodeFirstApproch.Models.Victim_Management.WitnessInfo", b =>
                {
                    b.Property<int>("WitnessInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WitnessInfoId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profession")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VictimCaseApplyId")
                        .HasColumnType("int");

                    b.HasKey("WitnessInfoId");

                    b.HasIndex("VictimCaseApplyId");

                    b.ToTable("WitnessInfos");
                });

            modelBuilder.Entity("FinalProjectCodeFirstApproch.Models.Weapon_Management.WeaponCategory", b =>
                {
                    b.Property<int>("WeaponCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WeaponCategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("WeaponCategoryId");

                    b.ToTable("WeaponCategories");
                });

            modelBuilder.Entity("FinalProjectCodeFirstApproch.Models.Weapon_Management.WeaponInfo", b =>
                {
                    b.Property<int>("WeaponInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WeaponInfoId"));

                    b.Property<DateTime?>("AcquisitionDate")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WeaponInfoId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Weapons");
                });

            modelBuilder.Entity("FinalProjectCodeFirstApproch.Models.Criminal_Management.CriminalActivity", b =>
                {
                    b.HasOne("FinalProjectCodeFirstApproch.Models.Criminal_Management.CriminalInfo", "CriminalInfo")
                        .WithMany("CriminalActivities")
                        .HasForeignKey("CriminalId");

                    b.Navigation("CriminalInfo");
                });

            modelBuilder.Entity("FinalProjectCodeFirstApproch.Models.Criminal_Management.CriminalContact", b =>
                {
                    b.HasOne("FinalProjectCodeFirstApproch.Models.Criminal_Management.CriminalInfo", "CriminalInfo")
                        .WithMany("CriminalContacts")
                        .HasForeignKey("CriminalId");

                    b.Navigation("CriminalInfo");
                });

            modelBuilder.Entity("FinalProjectCodeFirstApproch.Models.Criminal_Management.CriminalInfo", b =>
                {
                    b.HasOne("FinalProjectCodeFirstApproch.Models.Police_Management.CaseInfo", "CaseInfo")
                        .WithMany("Criminals")
                        .HasForeignKey("CaseId");

                    b.HasOne("FinalProjectCodeFirstApproch.Models.Suspect_Management.SuspectInfo", "SuspectInfo")
                        .WithMany("Criminals")
                        .HasForeignKey("SuspectId");

                    b.Navigation("CaseInfo");

                    b.Navigation("SuspectInfo");
                });

            modelBuilder.Entity("FinalProjectCodeFirstApproch.Models.Criminal_Management.PrisonRecords", b =>
                {
                    b.HasOne("FinalProjectCodeFirstApproch.Models.Criminal_Management.CriminalInfo", "CriminalInfo")
                        .WithMany("PrisonRecords")
                        .HasForeignKey("CriminalId");

                    b.HasOne("FinalProjectCodeFirstApproch.Models.Criminal_Management.Prison", "Prison")
                        .WithMany("PrisonRecords")
                        .HasForeignKey("PrisonId");

                    b.Navigation("CriminalInfo");

                    b.Navigation("Prison");
                });

            modelBuilder.Entity("FinalProjectCodeFirstApproch.Models.Investigation_Management.InvestigationInfo", b =>
                {
                    b.HasOne("FinalProjectCodeFirstApproch.Models.Police_Management.CaseInfo", "CaseInfo")
                        .WithMany("InvestigationInfos")
                        .HasForeignKey("CaseId");

                    b.HasOne("FinalProjectCodeFirstApproch.Models.System_Administration.PoliceUser", "PoliceUser")
                        .WithMany()
                        .HasForeignKey("OfficerId");

                    b.Navigation("CaseInfo");

                    b.Navigation("PoliceUser");
                });

            modelBuilder.Entity("FinalProjectCodeFirstApproch.Models.Investigation_Management.ReportAnalysis", b =>
                {
                    b.HasOne("FinalProjectCodeFirstApproch.Models.Police_Management.CaseInfo", "CaseInfo")
                        .WithMany("ReportAnalyses")
                        .HasForeignKey("CaseId");

                    b.HasOne("FinalProjectCodeFirstApproch.Models.System_Administration.PoliceUser", "PoliceUser")
                        .WithMany()
                        .HasForeignKey("OfficerId");

                    b.Navigation("CaseInfo");

                    b.Navigation("PoliceUser");
                });

            modelBuilder.Entity("FinalProjectCodeFirstApproch.Models.Police_Management.CaseInfo", b =>
                {
                    b.HasOne("FinalProjectCodeFirstApproch.Models.System_Administration.PoliceUser", "PoliceUser")
                        .WithMany()
                        .HasForeignKey("PoliceId");

                    b.HasOne("FinalProjectCodeFirstApproch.Models.Suspect_Management.SuspectInfo", "SuspectInfo")
                        .WithMany("CaseInfos")
                        .HasForeignKey("SuspectId");

                    b.HasOne("FinalProjectCodeFirstApproch.Models.Victim_Management.VictimCaseApply", "VictimCaseApply")
                        .WithMany("CaseInfos")
                        .HasForeignKey("VictimId");

                    b.HasOne("FinalProjectCodeFirstApproch.Models.Victim_Management.WitnessInfo", "WitnessInfo")
                        .WithMany("CaseInfos")
                        .HasForeignKey("WitnessId");

                    b.Navigation("PoliceUser");

                    b.Navigation("SuspectInfo");

                    b.Navigation("VictimCaseApply");

                    b.Navigation("WitnessInfo");
                });

            modelBuilder.Entity("FinalProjectCodeFirstApproch.Models.Police_Management.ReportsInfo", b =>
                {
                    b.HasOne("FinalProjectCodeFirstApproch.Models.Police_Management.CaseInfo", "CaseInfo")
                        .WithMany("ReportsInfos")
                        .HasForeignKey("CaseId");

                    b.HasOne("FinalProjectCodeFirstApproch.Models.System_Administration.PoliceUser", "PoliceUser")
                        .WithMany()
                        .HasForeignKey("OfficerId");

                    b.Navigation("CaseInfo");

                    b.Navigation("PoliceUser");
                });

            modelBuilder.Entity("FinalProjectCodeFirstApproch.Models.Police_Management.StationInfo", b =>
                {
                    b.HasOne("FinalProjectCodeFirstApproch.Models.System_Administration.PoliceUser", "PoliceUser")
                        .WithMany()
                        .HasForeignKey("PoliceId");

                    b.Navigation("PoliceUser");
                });

            modelBuilder.Entity("FinalProjectCodeFirstApproch.Models.Suspect_Management.EvidenceInfo", b =>
                {
                    b.HasOne("FinalProjectCodeFirstApproch.Models.Police_Management.CaseInfo", "Case")
                        .WithMany("EvidenceInfos")
                        .HasForeignKey("CaseId");

                    b.Navigation("Case");
                });

            modelBuilder.Entity("FinalProjectCodeFirstApproch.Models.Suspect_Management.InterrogationsInfo", b =>
                {
                    b.HasOne("FinalProjectCodeFirstApproch.Models.Police_Management.CaseInfo", "Case")
                        .WithMany("InterrogationsInfos")
                        .HasForeignKey("CaseId");

                    b.HasOne("FinalProjectCodeFirstApproch.Models.System_Administration.PoliceUser", "PoliceUser")
                        .WithMany()
                        .HasForeignKey("OfficerId");

                    b.HasOne("FinalProjectCodeFirstApproch.Models.Suspect_Management.SuspectInfo", "Suspect")
                        .WithMany("InterrogationsInfos")
                        .HasForeignKey("SuspectId");

                    b.Navigation("Case");

                    b.Navigation("PoliceUser");

                    b.Navigation("Suspect");
                });

            modelBuilder.Entity("FinalProjectCodeFirstApproch.Models.Suspect_Management.SuspectContact", b =>
                {
                    b.HasOne("FinalProjectCodeFirstApproch.Models.Suspect_Management.SuspectInfo", "Suspect")
                        .WithMany("SuspectContacts")
                        .HasForeignKey("SuspectId");

                    b.Navigation("Suspect");
                });

            modelBuilder.Entity("FinalProjectCodeFirstApproch.Models.Suspect_Management.SuspectInfo", b =>
                {
                    b.HasOne("FinalProjectCodeFirstApproch.Models.Victim_Management.VictimCaseApply", "VictimCaseApply")
                        .WithMany("SuspectInfos")
                        .HasForeignKey("VictimCaseApplyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VictimCaseApply");
                });

            modelBuilder.Entity("FinalProjectCodeFirstApproch.Models.System_Administration.PoliceRegistration", b =>
                {
                    b.HasOne("FinalProjectCodeFirstApproch.Models.System_Administration.Roles", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.HasOne("FinalProjectCodeFirstApproch.Models.Police_Management.StationInfo", "Station")
                        .WithMany("PoliceRegs")
                        .HasForeignKey("StationId");

                    b.Navigation("Role");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("FinalProjectCodeFirstApproch.Models.System_Administration.PoliceUser", b =>
                {
                    b.HasOne("FinalProjectCodeFirstApproch.Models.System_Administration.PoliceIdentities", "PoliceIdentities")
                        .WithMany()
                        .HasForeignKey("PoliceIdentitiesId");

                    b.Navigation("PoliceIdentities");
                });

            modelBuilder.Entity("FinalProjectCodeFirstApproch.Models.Victim_Management.VictimCaseApply", b =>
                {
                    b.HasOne("FinalProjectCodeFirstApproch.Models.Victim_Management.CrimeType", "CrimeType")
                        .WithMany("VictimsCaseApplies")
                        .HasForeignKey("CrimeTypeId");

                    b.Navigation("CrimeType");
                });

            modelBuilder.Entity("FinalProjectCodeFirstApproch.Models.Victim_Management.WitnessInfo", b =>
                {
                    b.HasOne("FinalProjectCodeFirstApproch.Models.Victim_Management.VictimCaseApply", "VictimCaseApply")
                        .WithMany("WitnessInfos")
                        .HasForeignKey("VictimCaseApplyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VictimCaseApply");
                });

            modelBuilder.Entity("FinalProjectCodeFirstApproch.Models.Weapon_Management.WeaponInfo", b =>
                {
                    b.HasOne("FinalProjectCodeFirstApproch.Models.Weapon_Management.WeaponCategory", "Category")
                        .WithMany("Weapons")
                        .HasForeignKey("CategoryId");

                    b.HasOne("FinalProjectCodeFirstApproch.Models.System_Administration.PoliceUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");

                    b.Navigation("Category");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("FinalProjectCodeFirstApproch.Models.Criminal_Management.CriminalInfo", b =>
                {
                    b.Navigation("CriminalActivities");

                    b.Navigation("CriminalContacts");

                    b.Navigation("PrisonRecords");
                });

            modelBuilder.Entity("FinalProjectCodeFirstApproch.Models.Criminal_Management.Prison", b =>
                {
                    b.Navigation("PrisonRecords");
                });

            modelBuilder.Entity("FinalProjectCodeFirstApproch.Models.Police_Management.CaseInfo", b =>
                {
                    b.Navigation("Criminals");

                    b.Navigation("EvidenceInfos");

                    b.Navigation("InterrogationsInfos");

                    b.Navigation("InvestigationInfos");

                    b.Navigation("ReportAnalyses");

                    b.Navigation("ReportsInfos");
                });

            modelBuilder.Entity("FinalProjectCodeFirstApproch.Models.Police_Management.StationInfo", b =>
                {
                    b.Navigation("PoliceRegs");
                });

            modelBuilder.Entity("FinalProjectCodeFirstApproch.Models.Suspect_Management.SuspectInfo", b =>
                {
                    b.Navigation("CaseInfos");

                    b.Navigation("Criminals");

                    b.Navigation("InterrogationsInfos");

                    b.Navigation("SuspectContacts");
                });

            modelBuilder.Entity("FinalProjectCodeFirstApproch.Models.Victim_Management.CrimeType", b =>
                {
                    b.Navigation("VictimsCaseApplies");
                });

            modelBuilder.Entity("FinalProjectCodeFirstApproch.Models.Victim_Management.VictimCaseApply", b =>
                {
                    b.Navigation("CaseInfos");

                    b.Navigation("SuspectInfos");

                    b.Navigation("WitnessInfos");
                });

            modelBuilder.Entity("FinalProjectCodeFirstApproch.Models.Victim_Management.WitnessInfo", b =>
                {
                    b.Navigation("CaseInfos");
                });

            modelBuilder.Entity("FinalProjectCodeFirstApproch.Models.Weapon_Management.WeaponCategory", b =>
                {
                    b.Navigation("Weapons");
                });
#pragma warning restore 612, 618
        }
    }
}
